### Read classes
GET http://localhost:3000/classes

### Read class
GET http://localhost:3000/classes/1

### Create class
POST http://localhost:3000/classes
Content-Type: application/json

{
    "name": "Warrior",
    "townId": 4
}

### Update class
PUT http://localhost:3000/classes
Content-Type: application/json

{
    "id": 2,
    "name": "Knight",
    "townId": 4
}

### Delete class
DELETE http://localhost:3000/classes/1
