### Read specialitys
GET http://localhost:3000/specialitys

### Read speciality
GET http://localhost:3000/specialitys/5

### Create speciality
POST http://localhost:3000/specialitys
Content-Type: application/json

{
    "name": "Gold"
}

### Update speciality
PUT http://localhost:3000/specialitys
Content-Type: application/json

{
    "id": 3,
    "name": "Logistic"
}

### Delete speciality
DELETE http://localhost:3000/specialitys/4
