### Read towns
GET http://localhost:3000/towns

### Read town
GET http://localhost:3000/towns/5

### Create town
POST http://localhost:3000/towns
Content-Type: application/json

{
    "name": "Castle"
}

### Update town
PUT http://localhost:3000/towns
Content-Type: application/json

{
    "id": 1,
    "name": "Bastion",
}

### Delete town
DELETE http://localhost:3000/towns/4
